version: '3'
services:
  couchdb-server:
    image: couchdb:3.3.3
    restart: unless-stopped
    ports:
      - "5984:5984"
    volumes:
        - /home/ubuntu/couchdb-data:/opt/couchdb/data
    env_file:
      - couchdb-startup.env
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  couchdb-startup:
    image: iqtlabs/edgetech-couchdb-startup:latest
    build:
      context: ./couchdb-startup
      dockerfile: ./Dockerfile
    restart: "unless-stopped"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
    depends_on:
      - couchdb-server
    env_file:
      - path: ./couchdb-startup.env
        required: false
